INSERT INTO subscription_categories (name, description) VALUES 
('Entertainment', 'Streaming services, media subscriptions'),
('Software', 'Online tools and services'),
('Utilities', 'Essential digital services'),
('Productivity', 'Work-related tools'),
('Fitness', 'Health and wellness subscriptions'),
('Education', 'Learning platforms and courses'),
('Other', 'Miscellaneous subscriptions'),
('Food & Drink', 'Meal delivery services, coffee subscriptions'),
('Shopping', 'E-commerce subscriptions'),
('News', 'Digital news and magazine subscriptions'),
('Gaming', 'Online gaming services'),    
('Music', 'Music streaming services'),
('Books', 'E-book and audiobook subscriptions'),    
('Travel', 'Travel and transportation services'),
('Finance', 'Financial services and subscriptions'),
('Health', 'Healthcare and medical subscriptions'),
('Beauty', 'Beauty and grooming subscriptions'),
('Home', 'Home and lifestyle subscriptions'),
('Fashion', 'Clothing and fashion subscriptions'),
('Sports', 'Sports and fitness subscriptions'),
('Kids', 'Children''s entertainment and education subscriptions'),
('Pets', 'Pet care and supplies subscriptions'),
('Tech', 'Technology and gadget subscriptions'),
('Automotive', 'Vehicle-related subscriptions'),
('Business', 'Professional services and subscriptions'),
('Hobbies', 'Recreational activities and hobbies'),
('Social', 'Social media and networking subscriptions'),
('Charity', 'Donations and charitable subscriptions'),
('Events', 'Event tickets and subscriptions'),
('Photography', 'Photography and design subscriptions'),
('Streaming', 'Video and music streaming services'),
('Communication', 'Messaging and communication services'),
('Transportation', 'Ride-sharing and transportation services'),
('Insurance', 'Insurance and protection services'),
('Gym', 'Gym and fitness memberships'),
('Subscription Boxes', 'Monthly subscription boxes and services'),
('Legal', 'Legal services and subscriptions'),
('Real Estate', 'Real estate and property subscriptions'),
('Investing', 'Investment and financial planning services'),
('Travel', 'Travel and vacation subscriptions'),
('Outdoor', 'Outdoor and adventure subscriptions'),
('DIY', 'Do-it-yourself and home improvement subscriptions'),
('Art', 'Art and creative subscriptions'),
('Crafts', 'Crafting and DIY subscriptions'),
('Gardening', 'Gardening and plant subscriptions'),
('Cooking', 'Cooking and meal prep subscriptions'),
('Parenting', 'Parenting and family subscriptions'),
('Wedding', 'Wedding and event planning subscriptions'),
('Music', 'Music lessons and instrument subscriptions'),
('Language', 'Language learning and translation services'),
('Writing', 'Writing and publishing subscriptions'),
('Design', 'Design and creative software subscriptions'),
('Marketing', 'Marketing and advertising subscriptions'),
('Sales', 'Sales and CRM subscriptions'),
('HR', 'Human resources and recruiting subscriptions'),
('Accounting', 'Accounting and finance subscriptions'),
('Consulting', 'Consulting and professional services'),
('Freelance', 'Freelance and gig economy subscriptions'),
('E-commerce', 'Online store and e-commerce subscriptions'),
('SaaS', 'Software as a Service (SaaS) subscriptions'),
('Cloud', 'Cloud computing and storage services'),
('Web Hosting', 'Website hosting and domain subscriptions'),
('Domain', 'Domain registration and management services'),
('Email', 'Email marketing and automation services'),
('Social Media', 'Social media management and analytics services'),
('SEO', 'Search engine optimization and marketing services'),
('PPC', 'Pay-per-click advertising services'),
('Content Marketing', 'Content creation and marketing services'),
('Video Production', 'Video editing and production services'),
('Graphic Design', 'Graphic design and branding services');